In [5]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import pyplot as plt
from sklearn.decomposition import PCA

import matplotlib as plt
from matplotlib.pyplot import imread
import numpy as np


A = np.random.rand(4, 4) # 4 instances, 4 features
B = np.dot(A, A.transpose())
print(B)

samples = 500
covariance_matrix = B
X = np.random.multivariate_normal(mean=[0,0,0,0], cov=covariance_matrix, size=samples) # instances 4 dimensional
print(X[0])


pca = PCA(n_components=4).fit(X)
# Now let’s take a look at our components and our explained variances:
print(pca.components_)
print(f'explained var: {pca.explained_variance_ratio_}')

pca_2 = PCA(n_components=2).fit(X)
transformed = pca_2.fit_transform(X)
plt.scatter(transformed.T[0], transformed.T[1])


from mpl_toolkits import mplot3d
pca_3 = PCA(n_components=3).fit(X)
transformed = pca_3.fit_transform(X)
#fig = plt.figure()
#ax = plt.axes(projection = '3d')
#ax.scatter(transformed.T[0], transformed.T[1], transformed.T[2], alpha=0.3)

from matplotlib.pyplot import imread
img = imread("data/train/cat.0.jpg")
img = img.astype(np.uint8)
print(img.shape)
img = img.mean(axis=2)
plt.imshow(img, cmap="gray")




[[2.64026222 1.33094283 0.84852605 1.52964997]
 [1.33094283 0.76019405 0.3142315  0.69913365]
 [0.84852605 0.3142315  0.44754506 0.63662687]
 [1.52964997 0.69913365 0.63662687 1.41164747]]
[0.82482786 0.32882904 0.32629563 0.45356862]
[[ 0.74168665  0.35786165  0.26853331  0.49972574]
 [-0.38840895 -0.45757398  0.31199096  0.73649588]
 [-0.23176638  0.41279436 -0.75483381  0.45399459]
 [ 0.49530167 -0.70154252 -0.51066371  0.04167635]]
explained var: [0.87787009 0.09327968 0.02773365 0.00111658]


AttributeError: module 'matplotlib' has no attribute 'scatter'